### ISSUE TITLE
Tube color unchanged after Python Trace

### ISSUE THREAD

**Issue by kamakshidasan** [topology-tool-kit/ttk#132] opened 2018-07-08 08:20 UTC
This is one of those small pesky issues.

Steps to reproduce this:

- Start trace
- Open a VTK file
- Apply FTM
- On the arcs, extract surface and apply tubes filter
- On the tubes apply a solid color
- Stop trace

If you run the above python trace as paraview --script=*.py back again, you will see that the tube color has changed back to original state, based on SegmentationId.

**Comment by julien-tierny** [comment] 2018-07-08 11:01
@CharlesGueunet:
can you take care of this please?
thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment] 2018-07-08 11:02
at first glance, looks like an upstream issue though (not necessarily ttk)
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment] 2018-07-09 11:15
hi,

I reproduced the issue and I confirm this is an upstream issue. 
the color change is well recorded in the generated python script but it is not 
correctly interpreted by paraview. I suggest you contact the paraview dev team 
if you want this to be fixed.
a workaround consists in saving your pipeline in pvsm state file format, which 
is the preferred pipeline IO in paraview.

I'll go ahead and close this one then.
thanks.
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Closed by julien-tierny** 2018-07-09 11:15 UTC
