### ISSUE TITLE
Persistence Diagram Bug with Multiple Executions

### ISSUE THREAD

**Issue by JonasLukasczyk** [topology-tool-kit/ttk#515] opened 2020-10-13 14:37 UTC
Hi all,
@floWetzels and I noticed that ttkPersistenceDiagram behaves strangely if it is tasked to process a vtkMultiBlockDataSet.

Actually, VTK out of the box checks if a filter can consume a vtkMultiBlockDataSet (by explicitly mentioning it in INPUT_REQUIRED_DATA_TYPE), and if yes the pipeline feeds the entire vtkMultiBlockDataSet into the RequestData method. However, if the filter does not support vtkMultiBlockDataSets (as in the case of ttkPersistenceDiagram), the pipeline will actually iterate over the blocks and feed them one by one into the RequestData method, and collect the individual results in a new vtkMultiBlockDataSet. This is intended behavior.

However, ttkPersistenceDiagram seems to have problems with multiple executions and messes up the outputs. My guess is that the root of the problem is the member variable `std::vector<ttk::PersistencePair> CTDiagram_{};`. Is there a need for this member variable? Theoretically the filter should just compute the output based on its input and then forget everything (be stateless). My guess is that the filter tries to cache some information and that messes up multiple executions.

I attached a minimal statefile that requires the ttk-data repository.  To see the bug, press the execute button of the ttkPersistenceDiagram filter. You should see some lines below the diagonal.

Best
Jonas

[diagram.pvsm.zip](https://github.com/topology-tool-kit/ttk/files/5372059/diagram.pvsm.zip)

![bug](https://user-images.githubusercontent.com/24282273/95875405-46314900-0d72-11eb-9dc5-1e9490c96db6.png)

**Comment by julien-tierny** [comment] 2020-10-15 12:24
@pierre-guillou 
could you have a quick look into this?
(this looks like an update issue with the vtk layer)

**Comment by pierre-guillou** [comment] 2020-10-15 12:34
Hi Jonas,
In fact, we store the `CTDiagram_` member variable to switch faster between the "diagram" view and the "embedded" view without recomputing the diagram.
That said, I have been able to reproduce this bug from your state file by switching back and forth between the two views. The second time I got the "diagram" view, pairs under the diagonal appeared.

**Comment by pierre-guillou** [comment] 2020-10-15 13:21
So, after some code manipulations & thinking, seems to me that the `CTDiagram_` stores the last iteration of the vtkMultiBlockDataset and switching back and forth between the two representations uses the correct scalar field arrays but keep the `CTDiagram_` unmodified, since the scalar field arrays have not been updated.

If we want to keep the fast switching between the two representations, we could
* either replace the vector of pairs with a `map<scalar field pointer, vector of pairs>` (and pray to have enough RAM to keep all the diagrams stored in one place)
* or clear the pairs vector if we (can) detect that the input is a multi-block dataset.

I would prefer to go with the second solution but I don't know (yet) how to check that the input data we receive in `ttkPersistenceDiagram::RequestData` is a block from a MultiBlockDataSet. Do have an idea how to do that, @JonasLukasczyk?

**Comment by JonasLukasczyk** [comment] 2020-10-15 13:31
What I think would be cool is if we would have a ttkPersistencePairs filter that always computes the spatial embedding, and we have another filter ttkPersistenceDiagram that does the 2D embedding + diagonal. What do you think?

**Comment by JonasLukasczyk** [comment] 2020-10-15 13:32
So the ttkPersistenceDiagram does not recompute pairs.

**Comment by julien-tierny** [comment] 2020-10-31 09:36
isn't that one fixed by #520 ?

**Comment by pierre-guillou** [comment] 2020-10-31 09:43
Sadly not. I just fixed some issues occurring on my laptop when PersistenceDiagram segfaulted in the dimension reduction states when the python script was not found.
The class member storing pairs for fast switching between the two representations still exists.
The only way to solve this is to give up on this class member, either by giving up on this fast switching mechanism, or by splitting the filter in two, as Jonas suggested: one filter for the diagram representation and one for the embedded representation, although we could also have a filter that converts from the diagram to the embedded representation.

**Closed as completed** 2020-11-14 15:27 UTC
