### ISSUE TITLE
Problem with Packaging and Local Installations

### ISSUE THREAD

**Issue by JonasLukasczyk** [topology-tool-kit/ttk#532] opened 2020-11-13 19:21 UTC
Hi all (@julien-tierny , @pierre-guillou, @CharlesGueunet  ),
today I tried to locally install a fresh dev-branch on my system as I was used to, but ParaView is now unable to load the ttk PlugIn (details about my installation procedure are listed below). I have the feeling this is related to the packaging procedure we discussed at the last dev meetup. It was my understanding that local installations will work as before, but it seems I'm missing now a step:

1) Build PV 5.8 and install it in some local folder called `CMAKE_INSTALL_PREFIX=ParaViewInstallDir`
2) Build TTK-dev with `ParaView_DIR=ParaViewInstallDir/lib/cmake/paraview-5.8`
and install in `CMAKE_INSTALL_PREFIX=ttkInstallDir`
3) Run ParaView and manually load plugin via manager.

Step 3 fails now. If I try to load `ttkInstallDir/lib/paraview-5.8/plugins/TopologyToolKit/TopologyToolKit.so` I get the following msg followed by a segfault:
`vtkSIProxyDefinitionMan:934    ERR| vtkSIProxyDefinitionManager (0x565156897450): Failed to locate base proxy definition (sources, ttkGaussianPointCloud). Aborting for debugging purposes.`

If I try to load `ttkInstallDir/bin/plugins/TopologyToolKit//TopologyToolKit.so` I don't get a segfault, but the msg `libttkBaseblank.so: cannot open shared object file: No such file or directory`. I tried adding the local folders to my LD_LIBRARY_PATH that contains all these so files, but that didn't work. Can someone help me figure this out?

Best
Jonas

**Comment by pierre-guillou** [comment] 2020-11-14 10:22
Hi Jonas,

As discussed in the TTK dev meetings, I changed the installation folder of the TTK libraries to a more generic location (`$prefix/lib`) and renamed the base libraries to avoid name collisions, so the LD_LIBRARY_PATH variable must definitely be modified accordingly (c.f. #517).

That said, I am for now unable to reproduce your issue. Since I already have a local ParaView install, I also tried to make a local TTK install, unset my PV_PLUGIN_PATH and point LD_LIBRARY_PATH to this folder and I'm able to load the TopologyToolKit.so plugin from the ParaView Plugin Manager without errors. Does it work with the PV_PLUGIN_PATH variable set?

I also have noticed that ParaView, in the plugin manager, with PV_PLUGIN_PATH unset, seems to remember the path to the TTK plugin from the last time it was loaded. Have you tried to remove this old plugin before `Load New`?

An other idea, it might be related to the fact that the configuration process is still influenced by the PV_PLUGIN_PATH environment variable: if it is set, you might end up with several plugins installed, as is seems to be in your case (one in `$prefix/lib/paraview-5.8/plugins` and one in `$prefix/bin/plugins`, which should be the default location). Can your try reconfiguring from scratch with an unset PV_PLUGIN_PATH?

Pierre

**Comment by JonasLukasczyk** [comment] 2020-11-14 11:34
Hi,
thanks Pierre for the quick feedback!

I'm now able to load the plugin in the **bin** folder after setting `LD_LIBRARY_PATH=ttkInstallDir/lib/`. I'm not able to load the PlugIn in the lib folder (still segfaults), but I guess this is not intended anymore. My PV_PLUGIN_PATH was/is unset, so is it intentional/necessary that we have two plugins in the install folder? I guess if PV_PLUGIN_PATH is set then we **additionally** install a copy of the plugin in that folder so that PV can find the plugin automatically, correct? So what is the purpose of the PlugIn in the lib folder?

Thanks again!
Jonas

**Comment by pierre-guillou** [comment] 2020-11-14 11:49
I think that the duplicate plugin under `lib/paraview-5.8` comes from having PV_PLUGIN_PATH set the first time you configure a new build directory. The TTK_INSTALL_PLUGIN_DIR CMake variable will inherit PV_PLUGIN_PATH and will install the plugin twice, one in `bin/plugins` and a second in TTK_INSTALL_PLUGIN_DIR (as explained in https://github.com/topology-tool-kit/ttk/pull/517#discussion_r514965418).
Having TTK_INSTALL_PLUGIN_DIR still following PV_PLUGIN_PATH when set is a leftover from the previous installation scheme for compatibility.

**Comment by JonasLukasczyk** [comment] 2020-12-07 13:55
@pierre-guillou @julien-tierny 
I guess we can close this issue, but some people found it helpful as a guideline on how to upgrade their installation. Should we put this on the installation webpage or something?

Best
Jonas

**Comment by JonasLukasczyk** [comment] 2021-02-09 11:27
Hi @pierre-guillou,
I'm helping @emmwel to install TTK on a linux machine but we are getting weird errors the first time we run cmake. We turned everything off (explicitly the standalone apps, the paraview plugin, the vtk wrappers) but we still get the following error msgs for each base code module (here we show only the first three):

-- Boost version: 1.67.0
-- Found the following Boost libraries:
--    system
-- GraphViz found
-- Found SQLITE3: /usr/lib/x86_64-linux-gnu/libsqlite3.so
-- Could NOT find Python3 (missing: NumPy) (found version "3.7.5")
-- Improper Python/NumPy setup. Disabling scikit-learn support in TTK.
CMake Error at CMake/BaseCode.cmake:45 (install):
   install TARGETS given no LIBRARY DESTINATION for shared library target
   "abstractMorseSmaleComplex".
Call Stack (most recent call first):
   core/base/abstractMorseSmaleComplex/CMakeLists.txt:1 (ttk_add_base_library)


CMake Error at CMake/BaseCode.cmake:45 (install):
   install TARGETS given no LIBRARY DESTINATION for shared library target
   "abstractTriangulation".
Call Stack (most recent call first):
   core/base/abstractTriangulation/CMakeLists.txt:1 (ttk_add_base_library)


CMake Error at CMake/BaseCode.cmake:45 (install):
   install TARGETS given no LIBRARY DESTINATION for shared library target
   "auction".
Call Stack (most recent call first):
   core/base/auction/CMakeLists.txt:1 (ttk_add_base_library)

-------------------------------------------------------------------------------
Do you have any idea why this is happening? Could this be an outdated cmake version or something?

Best
Jonas

**Comment by julien-tierny** [comment] 2021-02-09 11:31
> Do you have any idea why this is happening? Could this be an outdated cmake version or something?
looks like it.
what version are you guys using?
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JonasLukasczyk** [comment] 2021-02-09 11:32
cmake 3.13.4

**Comment by julien-tierny** [comment] 2021-02-09 11:44
that looks fairly old indeed.
the oldest version I have at hand is 3.17.4 and things configure fine.

maybe we should bump up the cmake requirements.

@kappe-c: you commented the root CMakeLists.txt indicating that the configuration succeeded with cmake 3.12.2
would you still happen to have that version at hand? 
if so, could you try to configure the current dev branch?

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JonasLukasczyk** [comment] 2021-02-09 11:45
We just manually installed cmake 3.19.4 and now it works. Seems like we should increase the minimum required cmake version, but I'm not sure how old it can be exactly. But 3.13.4 is definitely too old xD

**Comment by pierre-guillou** [comment] 2021-02-09 11:54
The error seems to be related to commit da060f2a6f09cc8e78a015985d55631e593947bc in which I removed the `RUNTIME DESTINATION`, `LIBRARY DESTINATION` and `ARCHIVE DESTINATION` from the install command to the base libraries (`CMake/BaseCode.cmake`, l. 45-47). I thought that removing those statements would put generated libraries in default destination folders (`$prefix/bin` for Windows, `$prefix/lib` for Linux/macOS) but apparently this doesn't work for this particular version of CMake. Besides, when reading the documentation, these statements seem optional from at least CMake 3.12.

**Comment by pierre-guillou** [comment] 2021-02-09 12:28
Reading the release notes of [CMake 3.14](https://cmake.org/cmake/help/latest/release/3.14.html):

> The install(TARGETS) command learned how to install to an appropriate default directory for a given target type, based on variables from the GNUInstallDirs module and built-in defaults, in lieu of a DESTINATION argument.

So the current problem should disappear with CMake >=3.14

**Comment by kappe-c** [comment] 2021-02-10 09:41
Hello,
    i know i am late, sorry. FYI, the oldest version i have (easily)
      available is now also 3.17
    Am 09.02.21 um 12:44 schrieb Julien
      Tierny:
    
    
      
      that looks fairly old indeed.
      the oldest version I have at hand is 3.17.4 and things configure
      fine.
      
      maybe we should bump up the cmake requirements.
      
      @kappe-c: you commented the root CMakeLists.txt indicating that
      the configuration succeeded with cmake 3.12.2
      would you still happen to have that version at hand? 
      if so, could you try to configure the current dev branch?
      
      cheers,
      -- 
      Dr Julien Tierny
      CNRS Researcher
      Sorbonne Universite
      http://lip6.fr/Julien.Tierny
      
      On Tuesday, 9 February 2021 12:33:14 CET Jonas Lukasczyk wrote:
      > cmake 3.13.4
      > 
      > 
      
      
      
      
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/topology-tool-kit/ttk/issues/532#issuecomment-775879633",
"url": "https://github.com/topology-tool-kit/ttk/issues/532#issuecomment-775879633",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by julien-tierny** [comment] 2021-02-10 10:12
thanks all for your input. fixed with commit 730a6759.
cheers

**Closed as completed** 2021-02-10 10:13 UTC
