### ISSUE TITLE
Not able to run dragon.pvsm with complex objects 

### ISSUE THREAD

**Issue by jobordu** [topology-tool-kit/ttk#91] opened 2018-04-22 18:22 UTC
Hi, 

I'm having crashes using dragon.pvsm when testing other 3D models than the original dragon.vtu. 

Here's a model attached to reproduce the crash:
[glasses_front.zip](https://github.com/topology-tool-kit/ttk/files/1935922/glasses_front.zip)

Jonathan

**Comment by julien-tierny** [comment] 2018-04-24 04:36
hi jonathan,

thanks a lot for your feedback.

> I'm having crashes using dragon.pvsm when testing other 3D models than the
> original dragon.vtu.
> 
> Here's a model attached to reproduce the crash:
> [glasses_front.zip](https://github.com/topology-tool-kit/ttk/files/1935922/g
> lasses_front.zip)
thanks a lot.

it seems that this surface is not manifold.
the main branch of ttk includes new features that can detect and somehow 
repair this (with the modules ManifoldCheck and PointMerger respectively).

in the attached screenshot 'manifold.png', you'll see a zoom-in in a region 
that contains triangles (in purple) which are reported by the ManifoldCheck 
module to contain edges which are connected to more than 2 triangles.
unfortunately, this violates the manifold assumption on which rely most of ttk 
features.

the attached state file 'meshRepair.pvsm' repairs these triangles as seen in 
the screenshot. the manifold output surface is also attached 
('glasses_manifold.off').

once the surface is manifold, ttk features can be called on the object, as 
seen in the attached screenshot 'reebGraph.png', where the dragon demo state 
file has been reproduced from scratch.

note that ttk does not officially support Reeb graph computation for the 
moment. however, these objects can be computed in practice with the 
ContourForests plugin, by setting up a sufficiently high number of threads. 
this algorithm segments the data according to the range values into a number 
of segments equal to the number of threads (technically, half the number of 
threads). thus, if this number of segments is large enough, small loops are 
still captured, as seen in the screenshot. note that in principle, this range 
segmentation should still work as described above even if openmp is disabled 
(as it is currently the case under windows). 
you will find the corresponding state file attached ('glasses.pvsm').

the fact that the dragon demo state file does not work when given a different 
surface on its input seems to be an independent problem that we need to 
further investigate.

we'll keep you updated.

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment] 2018-05-11 15:10
hi jonathan,

fyi this example seems to run fine under Windows with our batchmode pvsm state 
checker (see my previous email). can you please run the state checker as well 
to see if you still observe the same issue?
also, please use ttk's master branch for your tests (that would ease debugging 
on our end).

thanks for letting us know.

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment] 2018-05-26 05:42
dear jonathan,

our nightly checks have reported that the latest version of ttk's sources 
(master branch with ParaView 5.5) now manages to complete this example 
successfully under windows.
thus I'll close this issue for now.
please feel free to re-open it if you run into any further issue.

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Closed** 2018-05-26 05:42 UTC
Labels: question
