### ISSUE TITLE
Generalization of ttkScalarFieldSmoother over various types of manifolds

### ISSUE THREAD

**Issue by jobordu** [topology-tool-kit/ttk#184] opened 2019-01-25 19:06 UTC
Hi, 

The Scalar Field Smoother is fast and quite convenient, however it seems to work only on 2-manifold.

Can it be extended to 1-manifold and possible to 3-manifold ? 

Best, 

Jonathan

**Comment by julien-tierny** [comment] 2019-01-26 07:39
hi jonathan,

thanks for your feedback.

> Can it be extended to 1-manifold and possible to 3-manifold ? 
I confirm that the scalar field smoother module is currently also working for 1 and 3-manifolds.
however, you must make sure that the input mesh on which the data is defined is a valid simplicial complex (i.e. tet-only mesh in 3D, i.e. sequence of 1-dimensional cells in 1D).

in practice, before you use this filter, I'd recommend to use the "Tetrahedralizer" filter from ParaView which guarantees exactly that (despite its name referring only to 3D).

so, as a rule of thumb, if you're dealing with meshes (for regular grids, it's not needed):
 "Tetrahedralizer" + "ScalarFieldSmoother" should work in 1D, 2D, 3D.
that comment is valid for all TTK modules by the way.

I hope this was helpful.
if you don't mind, I'm going to go ahead and close this one.
please feel free to re-open if you experience issues again.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment] 2019-01-27 10:16
hi jonathan,

thanks for your feedback.

I cannot reproduce the issue over here.
could you share the data you're having the issue with?

thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment] 2019-03-03 09:07
hi jonathan,

I'm going to go ahead and close that issue.
please feel free to re-open if needed.

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by mv740** [comment] 2019-04-23 16:32
Hi Julien,

We tried using this curve with the latest ttk, and the scalarfieldsmoother wasn't working

[Not_able_to_scalar_smooth_curve.zip](https://github.com/topology-tool-kit/ttk/files/3108639/Not_able_to_scalar_smooth_curve.zip)

**Comment by julien-tierny** [comment] 2019-04-24 14:13
hi michal,

thanks a lot for providing this test dataset.

it seems that the vtkPolyData class has some dimension dependent behaviors we had not anticipated.

the commit #ffd22f29218cca1aa5c269ff11e4108c3a39a80e should have fixed the issue. thanks for letting me know if that works out for you.

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by mv740** [comment] 2019-04-24 15:56
Hi, 

I have tested your fix and it's working! 

thanks

**Comment by julien-tierny** [comment] 2019-04-25 03:59
awesome, I'll close the issue then.
thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Closed** 2019-04-25 03:59 UTC
